In [8]:
import numpy as np

def solve_linear_equation(A, b):
   # enter your code here, and remove the following line (30%)
   rankA = np.linalg.matrix_rank(A)
   Ab = np.hstack((A,b))
   rankAb = np.linalg.matrix_rank(Ab)
   
   if(rankA == rankAb == 3):
     return 1
   
   if(rankA == rankAb <3):
     return 0
    
   if(rankA != rankAb):
     return -1

   return 0

def flag_to_message(flag):
   if flag == 1:
     print('The linear system Ax=b has only one solution.')
   elif flag == 0:
     print('The linear system Ax=b has infinitely many solutions.')
   elif flag == -1:
     print('The linear system Ax=b has no solutions.')
   else:
     print('Unknown flag!')

def get_input_data(input_id):
   if input_id == 'case1': 
     A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
     b = np.array([[-7], [-4], [2]])
   elif input_id == 'case2':
     A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
     b = np.array([[5], [7], [-8]])
   elif input_id == 'case3':
     A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
     b = np.array([[-15], [-5], [-5]])
   return A, b

if __name__ == '__main__':
   for case in ['case1', 'case2', 'case3']:
     A, b = get_input_data(case)
     print(case)
     print('A =', A, 'b =', b.T)
     flag = solve_linear_equation(A, b)
     flag_to_message(flag)
     if flag == 1:
       print('The solution is ', np.linalg.solve(A, b))
     print()

case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
The linear system Ax=b has infinitely many solutions.



In [9]:
# Can we use np.linalg.solve() to determine whether 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.
不能， np.linalg.solve() 只能解當方程式有唯一解的情形時

In [10]:
# Given matrix 𝐀 of dimension (m,n). If rank(𝐀)=𝑛, can we infer that 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.
rank(A)=只能確認行滿秩，但若b不在A的行空間中，則Ax=b無解